groups: 
    - developer
recipes:
    mac_os_x:
        - osxdefaults::dock_automatically_hide_and_show_the_dock
        - osxdefaults::dock_set_the_icon_size_of_dock_items_to_36_pixels
        - osxdefaults::dock_show_indicator_lights_for_open_applications_in_the_dock
        - osxdefaults::dock_position_the_dock_on_the_left_side
        - osxdefaults::finder_show_all_files
        - osxdefaults::finder_show_file_extensions
        - osxdefaults::expand_print_panel_by_default
        - osxdefaults::expand_save_panel_by_default
        - osxdefaults::prevent_time_machine_from_prompting_to_use_new_hard_drives_as_backup_volume
        - osxdefaults::menu_add_battery_percentage
        - osxdefaults::menu_show_clock_with_date
        - osxdefaults::menu_show_volume_icon
        - osxdefaults::set_a_blazingly_fast_keyboard_repeat_rate
        - osxdefaults::tap_to_click
        - osxdefaults::disable_auto_correct
        - osxdefaults::do_not_show_dashboard_as_a_space
        # add show dashboard on left lower corner
        - osxdefaults::finder_set_preferred_view_style
attributes:
    osxdefaults:
        terminal:
            color_scheme: 
        finder:
            preferred_view_style: clmv
    homebrewalt:
        apps: 
        cask_apps:
            - google_drive
            - vlc
            - keepingyouawake