groups:
recipes:
attributes:
    homebrewalt:
        apps:
            - activemq
            - maven
            - git
            - git-extras
        cask_apps:
            - sublime-text3
            - sourcetree
            - java
            - intellij-idea
            - virtualbox
            - vagrant
            - iterm2